### ISSUE TITLE
Question: How to apply default rules to all fields without specifying them?

### ISSUE THREAD

**Issue by justinpincar** [joonhocho/graphql-rule#2]
I was hoping that something like this would work, but trying to query any field on the returned object gives undefined. Having to specify all possible fields is a major PITA.

```
import _ from 'lodash';
import Rule from 'graphql-rule';

export default Rule.create({
  name: 'Partner',
  defaultRule: {
    preRead: (model) => {
      const partnerId = model.$data.id;
      const managedPartnerIds = model.$context.user.managedPartnerIds();
      const allowed = _.includes(managedPartnerIds, partnerId);
      return allowed;
    },
  },
});
```

Is there a way to accomplish this behavior?

**Comment by vergenzt** [comment]
I wonder if you have to specify `rules: {}` in addition to your `defaultRule`? Just a thought. No idea if it'll work. :)

**Comment by justinpincar** [comment]
Good idea, I didn't try that! Unfortunately, that doesn't work either though.

NBD, I can work around this for now - I just see issues down the road when someone forgets to update the rule/model definition when the corresponding one changes.

**Comment by joonhocho** [comment]
@justinpincar @vergenzt 
In the example,
```
const Model = Rule.create({
  name: 'Model',
  props: {
...
  },
  defaultRule: {
...
  },
  rules: {

    // use defaultRule settings
    authorId: {},

  },
});
```
